# Generated by Django 3.2.6 on 2021-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_choice_choice_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_password',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_username',
            field=models.CharField(default='', max_length=40),
        ),
    ]
